#+TITEL: 实用性阅读指南
* 阅读目的(2019-12-08 第一次阅读)
  掌握快速阅读实用性书籍的方式，并在实际中实施
* 总结
  - 阅读前：首先读书前明确目的(问题)。
  - 阅读中：然后以解答问题为导向，面向输出为原则，根据2/8原则，在了解概要情况后，直接阅读核心章节。阅读过程中，各种标记核心和重要的地方。
  - 阅读后：整理阅读笔记，进行输出。同时将所学付诸行动

  （本书内容极其简单，分讨论课题也很基础，没有深入介绍。阅读后只需记住先明确问题，再阅读，查工具书似的阅读，通过总结、输出和实践的方式进行巩固加深）

  其它有意思的地方：
  - 情感能加深记忆
  - 格外注意“重要不紧急”的事情
  - 将读书视为“自我指导”
* 阅读笔记正文
** 第一章：有效率地读书
*** 1、确定读书目的
    明确目的，知道自己“想从这本书里得到什么”，再去阅读，这样就能“集中火力”，更容易找到想知道的信息。
    把读书的目的设定得与“行动目标”相近一些。
*** 2、只摘取自己需要的信息
    想想好关于书本的“问题”，然后在书本中找出应对这些“问题”的答案：
    - 清楚明确自己的读书目的
    - 概览序言、目录、后记等部分，大概了解书的内容
    - 确定问题（考虑深入阅读的目的）
*** 3、通过序言、目录和后记掌握概要
    序言：浓缩了一本书所有的要点。作者的自我介绍、关于此书的想法、撰写的原因等，还有书籍主要内容和各章的总结。
    目录：目录解释了书的整体结构，看完目录便能够掌握一本书所有的内容。
    后记：（ *建议再阅读正文之前阅读* ）作者对全书的总结，编撰此书的感谢，有助于更加深刻理解作者的意图。
*** 4、要有时间意识
    理论：有时间意识的话，效率会迅速提高。
    将惯有的随意读书方式转变为安排时间阅读：
    - 先确定读完需要多少时间
    - 准备分几次完成
*** 5、不要试图全部理解
    认为一本书从头读到尾全部理解才是读书是错误的。根据2-8原则，一本书只有20%是重要的，其中的20%，即4%才是核心。（是不是即使大部头书，也毫无压力了）
，与其全部读完（甚至因为恐惧太多而读不完），完全不理解或不能够吸收，不如一开始就集火核心内容，精力花在刀刃上。
    当你通过这种方式尝到甜头，就不会觉得舍弃了部分内容而觉得不安。（真香定律）
*** 6、有意识地“输出”
    输出，即有组织整理的表达出来，可以“向他人讲述”，或者“写下来”。以“输出”为前提，阅读将会更有效率。同时输出的过程也是自己的再次理解和重构，加深记忆和理解（所谓教即为学）。
*** 7、争取多读
    并列读书，一天内不同时间阅读不同的书。书籍要精选，有意义，不重复的书。
    （这个要结合自己的时间和精力，太多容易精神涣散，每本书的本次不能阅读太少，不能还没有进入情景就需要出来，影响体验）
*** 8、不被他人的意见左右
    选书的时候，别人意见作为参考，自己多去实体店挑选。
    （综合参考别人和自己的想法，自己也会有盲区和主观偏见，不过去实体店和图书馆很建议）
*** 9、不借书
    （真正爱上阅读的时候，买喜欢的书）
** 第二章：边读边做笔记
*** 1、如何记录读书笔记
    通过“读书笔记”整理知识和信息，帮助加深记忆。通过反复阅读（笔记），加深理解和记忆。
    主要方式：
    - 首先挑重点：在书上“划线”，“标记号”，“注明文字”，“贴便签”，“书页折角”
    - 整理笔记：*思维导图*，（Org 文档也可以作为笔记，以可以输出为标准）
*** 2、把书弄脏也要记笔记
    （就是各种记笔记，划重点。这里可以采取自己喜欢的方式）
*** 3、如何制作读书笔记
    基本信息：
    - 本书书名
    - 作者
    - 笔记制作日期
    - 读书开始日
    - 读书终止日
    整理书的内容：
    - 直接摘录一部分重要内容块（注意控制内容大小）
    - 做摘要，分项罗列（浓缩总结重要内容）
    - 写下自己的感想（阅读过程中的感谢）
*** 4、把握书的结构层次
    掌握整体概况，找出写着自己想要信息的页码，直接阅读
    （整体信息只需要掌握粗略概要，通过阅读序言、目录或者每章节的引言即可。然后直接进入解答问题的章节阅读）
*** 5、什么是思维导图
    （可视化展现头脑中思考的内容，非重点）
*** 6、读书思维导图的制作方法
    （非本次目的，也不够专业全面，略）
*** 7、如何制作一本书的思维导图
    （非本次目的，也不够专业全面，略）
** 第三章：牢记读到的内容
*** 1、为什么记不住书中内容？
    （非本次目的，略）
*** 2、反复阅读，留存记忆
    （非本次目的，略）
*** 3、丢弃80%的内容，找出重要的20%
    （再次重申2/8定律）
*** 4、带着感情阅读
    理论：情感有助于加深记忆
*** 5、以向他人复述为前提来阅读
*** 6、整理成故事来记忆
    （谐音记忆、联想记忆等，本书只简单描述，不够专业）
*** 7、使用首字来记录文字
    （同上）
*** 8、创建形象，联想记忆
    （同上）
*** 9、便利贴记忆法
    （同上，还有抽象化的高级法：思维宫殿）
** 第四章：将书中内容付诸行动
*** 1、知识，只有付诸行动才可发挥效果
*** 2、将自我指导用于读书
    指导：引出对方的潜能，促使其自主行动的过程（保留意见）
*** 3、从书本上设定行动目标
    （对个人成长而言，重要不紧急的事情很关键，需要特别注意下）
*** 4、想象自己达成目标时的样子
    （自我激励）
*** 5、明确现在的位置
    （非本次目的，略）
*** 6、思考与行动目标之间的差距
    (同上)
*** 7、为了填补间距的具体行动
    (同上)
*** 8、从所写的项目中选出一项
    (同上)
*** 9、将行动细分成明天就能开始的小步骤
    (同上)
*** 10、确定需要实施的事情
    (同上)
*** 11、将行动告知他人
    (同上)
*** 12、付诸行动
    (同上)
** 第五章：读书对人生产生影响的实例
   (故事分享，全略)
*** 1、读书 + 创业
*** 2、读书 + 自我启发
*** 3、读书 + 考取资格证书
*** 4、读书 + 掌握领导力
*** 5、读书 + 提升工作技能
** 后记
** 出版后记
