#+TITLE: 你的灯亮着吗？发现问题的真正说所在
* 基本信息
  - 开始时间：（不知道具体时间，先浏览过，第二次整理笔记）
  - 结束时间：2020-02-21
  - 作者：唐纳德·高斯
  - 书名：你的灯亮着吗？发现问题的真正说所在
* 阅读目的
  学习关于解决问题的一般框架，纠正常犯错误，提高发现问题的洞察力
* 总结
  （略，另外专门写总结）
* 阅读笔记
** 第一部分：问题是什么？
*** 第一章 一个问题
    抑制匆匆解决问题的冲动，首先思考一下：谁遇到了问题？
    然后，对这个答案的每个答案都进一步探讨：问题的本质是什么？
*** 第二章 彼得发起了一个请愿
    问题的多方人员如果无法对问题本身达成一致，那么就不可能有大家都满意的解决方案。因此问题解决者需要致力于促进这个结果，比如让各方当面进行讨论。
*** 第三章 你的问题是什么
    问题就是理想状态和现实状态之间的差别。有时我们又无法真正明白问题到底是什么？直到我们彻底摆脱了这些问题。
** 第二部分：这次问题是什么？
*** 第四章 比利战胜投标人
    有时候别人会把自己真正问题隐藏起来，提出的需求实际是真正问题解决方案中，需求人无法或不愿解决的部分。所以我们 *不要把别人的解决方法作为定义问题的方法*
    此外，如果你解决问题太过神速，别人不相信你真的解决了问题。
    面对有利可图的问题时，道德考量很肯能就烟消云散了
*** 第五章 比利忍住没说
    别把问题的解决方案当做问题的定义，即使这个方案是自己提出来的。
*** 第六章 比利反思投标案
    *即使问题已经解决，你也无法确定你的问题定义是否正确*
    不要仓促下结论，但也不要忽视第一印象
    *面对问题时真正重要的一点在于，你要知道，问题是永远得不到解答的，但只要你一直在提出问题，就没有关系。只有当你自欺欺人地想，你已经找到了问题最终的、正确的定义的时候，你才会相信你找到了最终的解决方案。如果这么想，你可就错了，因为从没有什么东西是“最终的解决方案”*
    ===》 *你永远无法确定已经找到的问题定义是正确的，但是永远不要停下来寻找正确定义的脚步*  （人生亦是如此）
** 第三部分：问题到底是什么？
*** 第七章 无尽的链条
    任何一个问题都是理想状态和现实状态之间的差别，当人们通过改变抓哪个台“解决”一个问题的时候，常常会新制造一个或几个问题来 ==》 每一个解决方案都是下一个问题的来源。并且很多新问题都是无意识下生产的。因为某些问题最困难的部分就是发现问题存在。
    在任何一个问题定义中，都有几百个点有可能被忽略。如果连三个疑点都找不出来，那么你要么是不会思考，要么就是不愿意思考
*** 第八章 忽视不协调之处
    人类的适应能力非常之强，几乎可以容忍任何形式的不协调，除非他们意识到容忍问题不是唯一的办法，这时候麻烦就来了
    借助外国人、盲人、儿童来检验你给出的定义，或者让自己设身处地地站到外国人、盲人、儿童的角度上来检验。
    每次转换一次视角，都会发现新的不协调之处  ===》  把一项“解决方案” 付诸实践之前从各个视角对其审视一遍，不是等到出现灾难性后果才意识到问题存在
*** 第九章 找到问题所属的层面
    如果想得到不同的解决方案，该怎样变换问题的表述方式
    当你沿着定义问题的道路疲倦前行时，过一会儿就要回头看看，确认自己没有走错路
*** 第十章 注意你所表达的含义
    一旦你将一个问题描述拟成了文字，做些文字游戏，以确保每个人对问题的理解可以统一
** 第四部分：问题该由谁解决？
*** 第十一章 烟雾缭绕
    当别人可以妥善解决自己的问题时，不要越俎代庖。因为问题相关方对问题了解更深入、感受更真切，同时他们提出的解决方案之后，更愿意参与到执行中。
    如果是别人的问题，就把它当成别人的问题
*** 第十二章 校园停车难问题
    在社会上，很多问题源自于系统的设计者与决策者，他们并未亲身体会过应该由他们“负责人”的问题。   ==》如果一个人处于解决问题的位置，却并不受问题困扰，那就采取一些行动使他能够亲身体验到问题。
    *为了改变局面，试着把责任归到自己身上--哪怕一会儿也行*
*** 第十三章 隧道尽头的灯光
    将问题交给真正需要负责的人，有时候提供自认为合理的方案其实只会填麻烦。如果当局者没有意识到问题的存在，进行合适的提醒：你的灯亮着吗？
** 第五部分：问题来自哪里？
*** 第十四章 詹尼特。贾沃斯基遇上了混蛋
    如果我们把问题归于天性、官僚主义等上面时，意味着不能（其实是不愿意）去找到解决办法。如果我们能把问题的根源归结到人的身上，或者一些真实的物品、行为上时，就总有机会找到可行的解决办法。
*** 第十五章 麦特兹锡恩先生解决了问题
    大多数情况下，问题的根源在你自己身上。有时候我们会惊讶的发现：恶棍原来是英雄，而英雄原来是恶棍。
    找到问题的根源，往往问题就能迎刃而解。
*** 第十六章 找事让人做的人和领赏的人
    有时候，解决问题的过程、人员或者机构本身也可能成为问题。尤其本身是因为问题而存在的。比如：扶贫办，裁军委员会（需要很高的觉悟）
    世界上有两种人，意中人做事，另一种人领赏。做第一种人吧，那里的争斗比较少。
*** 第十七章 考试和其他谜题
    问题是谁出的？他想对我做什么？
** 第六部分：你真的想解决问题吗？
*** 第十八章 不怕累的汤姆被玩具耍了
    我们通常任务自己不善于解决问题，而事实上当我们知道了问题是什么后，解决问题常是不值一提的事情。
    常年的教育与经验让我们养成了习惯或本能。当我们遇到问题，会紧紧抓住首先发现的问题的表述，然后尽快“解决”塔。没有意识和功夫去思考问题到底是什么。当我们在解决不是问题的“问题”时，它对我们而言也成了真正的“问题”，而这一切都是个问题。
    无论表面上如何，在你提供他们所要求的东西之前，他们极少知道自己想要什么。
*** 第十九章 佩兴丝的计谋
    很多人是“为解决方案找问题”，想真正解决问题的人并不是很多。
*** 第二十章 一项优先任务
    在正式开始解决任何一个问题之前，每一位未来的问题解决者都应该问一问：我真的想找到解决方案吗？
    人们永远没有足够的时间把它做好，但永远有足够的时间重新来过  ===》人们永远没有足够的时间去考虑到底是不是想要它，但永远有足够的时间去为之后悔
