#+TITLE 系统之美
* 基本信息
  - 开始时间：2019-12-25
  - 结束时间：
  - 作者：德内拉.梅多斯
  - 译者：邱昭良
  - 书名：系统之美
* 阅读目的
  深入学习了解系统思维的定义和理念
  - 掌握核心概念
  - 应用场景及范围
  - 使用方式
  - 优缺点
* 总结
  （结合本次阅读目的，进行简短的总结）
* 阅读笔记
** 导读
** 引言：系统多棱镜
*** 无处不在的系统
    什么是系统？

    系统是一组相互连接的事物，在一定时间内，以特定的行为模式相互影响，例如人、细胞、分子等。系统可能受外力触发、驱动、冲击或限制，而系统对外力影响的反馈方式就是系统的特征。
*** 重塑系统，发现更大的世界
*** 找到属于你的系统之美
** 第一部分：系统的结构和行为
*** 第1章：系统之基础
**** 总体大于部分之和
     系统并不仅仅是一些事物的简单集合，而是一个由一组相互连接的要素构成的、能够实现某个目标的整体。

     从这一定义可见，任何一个系统都包括三种构成要件：要素、连接、功能或目标。
**** 从关注要素到透视游戏规则
     从细究要素转向探寻系统内在的连接关系，即研究那些把要素整合在一起的关系。

     系统中的很多连接是通过信息流进行运作的。信息使系统整合在一起，并对系统的运作产生重要影响。系统的连接有的是物质流、能量流或者信息流。

     一般说，改变要素对系统的影响是最小的。只要不触动系统的内在连接和总目标，即使替换掉所有的要素，系统也会保持不变，或者只是缓慢的变化。相反，如果内在的连接改变了，系统就会发生巨大的变化。同样功能或目标的改变也会对系统产生重大影响。
**** 理解系统行为的动态性
     “存量”是所有系统的基础。所谓存量，是指任何时刻都能观察、感知、计数和测量的系统要素。存量会随着时间的变化而不断改变，使其发生变化的就是“流量”。所谓流量，是一段时间内改变的状况。

     *由于存量的存在，流入量和流出量可以互相独立，并在一定时期内不必保持平衡或一致。这一原则可以引导我们直接了解反馈的概念*
**** 反馈：系统是如何运作的
     信息反馈控制系统是所有生物和人类行为的基础。一个反馈回路就是一条闭合的因果关系链，从某一个存量出发，并根据存量当时的状况，经过一系列决策、规则、物理法则或者行动，影响到与存量相关的流量，继续又反过来改变存量。
**** 自动洄游的鱼：调节回路
     在系统中，调节回路是保持平衡或达到特定目标的结构，也是 *稳定性和抵触变革的根源*
**** 脱缰的野马：增强回路
     第二类反馈回路的作用是不断放大、增强原有的发展态势，自我复制，它们是一个良性循环或者恶性循环。总之，增强回路会强化系统原有的变化态势。
*** 第2章：系统大观园
**** 单存量系统
     - 一个存量、两个相互制衡的调节回路的系统：温度调节器
     - 一个存量、一个增强回路以及一个调节回路的系统：人口和工业经济
     - 含有时间延迟的系统：库存

     系统之思：
     - 反馈回路所传递的信息只能影响未来的行为，不能立即改变系统当前的行为。因为信息经由反馈回路的传递需要时间，如果你根据当前反馈做出了一项决策，它不能够足够快的发送一个信号，去修正当前反馈所驱动的系统行为，这期间必然有一定的延迟。所以你的决策只能影响未来的行为，不能改变当前的系统行为。
     - 每个调节回路都有它的转折点，此时其他回路会取代该回路而居于主导地位，使存量远离它的目标且无法自动回到动态平衡状态
     - 调节回路上的时间延迟很可能导致系统的震荡
**** 双存量系统
     - 一个可再生性存量收到另外一个不可再生性存量约束的系统：石油经济
     - 有两个可再生性存量的系统：渔业经济

     系统之思：
     - 如果你构建的资本存量依赖于一项不可再生性资源，那么它增长的越高、越快，下跌得可能越深、越快。
** 第二部分：系统思考与我们
*** 第3章：系统之美：系统的3大特征
    如果土壤有机质作为一个整体是良好的，那么每个部分都是好的，不管你是否理解；如果生物圈在演进过程中，已经建立了我们喜欢单不了解的东西，那么只有杀光才会丢弃那些看似无用的部件。一个精细的钳工，首先想到的是确保每一个齿轮和车轴都完好无损。
**** 适应力
     适应力：如果形容一个系统，适应力指的是系统在多变的环境中保持自身的存在和运作的能力。与适应力相对的是脆弱性或刚性

     系统之思：
     - 系统之所以会有适应力，是因为系统内部结构存在很多互相影响的反馈回路，正是这些回路互相支撑，即使在系统遭受巨大的扰动时，仍然能够以多种不同的方式使系统恢复至原有状态。
     - 适应力总是有限度的。有适应力的系统可能是经常动态变化的。相反，一直保持恒定的系统恰恰是不具备适应力的。
     - 不能只关注系统的生产率或稳定率，也要重视其适应力，即自我修复或复位的能力，战胜干扰、恢复机能的能力。
**** 自组织
     自组织：系统所具备的使自生结构更加复杂化的能力

     系统之思：
     - 系统通常具有自组织的特性，具有塑造自身结构生成新结构、学习、多样化和复杂化的能力。即使是非常复杂的自组织形式，也有可能产生于相对箱单的组织规则
**** 层次性
     层次性：一个大的系统中包含很多子系统，一个子系统又可以分解成更多、更小的子系统。系统和子系统的这种包含和生成关系，被称为层次性。
     系统之思：
     - 层次性是系统的伟大发明，不只是因为他们使系统更加稳定和有适应力，而且 *因为他们减少了信息量，使得系统各部分更容易记录和跟进。*
     - 如果层级中每个层次内部和层次之间的信息连接设计合理的话，反馈延迟就会大大减小，没有哪个层次会产生信息过载。这样系统的运作效率和适应力就得以提高。
     - 系统的层次性表明系统是自下而上进化的，上一层及的目的是服务于较低层级的目的
*** 第4章：系统之奇：系统的6大障碍
    系统之思：
    - 系统结构是行为的根源，而系统行为体现为随时间而发生的一系列事件。
    - 我们认为自己所知道的关于这个世界的任何东西都只是一个模型。虽然我们的模型确实与世界高度一致，但远未达到完整地代表真实世界的程度。
**** 别被表现所迷惑
     系统结构是行为的根源，而系统行为体现为随时间而发生的一系列事件。系统思考需要反复审视结构和行为，善于系统思考的人会将二者联系起来，理解事件、行为以及结构之间的关系。
**** 在非线性的世界里，不要用线性的思维模式
     系统中的很多关系非线性的1，他们的相对优势变化与存量的变化是不成比例的。反馈系统中的非线性关系导致不同回路之间主导地位的转换，也相应地引起系统行为的复杂变化。
**** 恰当地划定边界
     系统最大的复杂性出现在边界上。边界上的无序、混杂，成为了多样化和创造力的根源所在。世界是普遍联系的，不存在孤立的系统。如何划定系统的边界，取决于你的分析目的，也就是我们想问的问题。
**** 看清各种限制因素
     在给定的一段时间内，对于系统来说，最重要的一项输入是限制或约束力度最大的那个因素。 *任何成长都存在限制，有些限制是自发的；而有些则是系统施加的。从根上讲，关键不是追求持续成长，而是选择在哪些因素的限制之下维持生存*
**** 无锁不在的时间延迟
**** 有限理性
     系统之思：
     - 有限理性意味着，人们会基于其中掌握的信息制定理性的决策，但是由于人们掌握的信息通常是有限的、不完整的，尤其对于系统中相隔较远或不熟悉的部分，由此导致他们的决策往往并非整体最优
     - 要想改变行为，首先跳出你所在系统中固有的位置，抛弃当时观察到的有限信息，力求看到系统整体的状况。从一个更广阔的视角来看，可以重构信息流、目标、激励或者限制因素，从而使分割的、有限的、理性的行动累加起来，产生每个人都期盼的结果
*** 第5章：系统之危与机：系统的8大陷阱与对策
****  政策阻力：治标不治本
      政策阻力来自于系统中各个参与者的有限理性，每个参与者都有自己的目标，都会对系统进行监控，观察一些重要变量的变化态势，并将其与自己的预期或目标进行对比。如果存在差异，每个产于者都会采取某些措施，试图扭转当前的局势，使其符合自己的预期或目标。一般来说，目标与实际状况之间的差异越大，行动的压力或强度就越大。

      应对策略:
      - 压制
      - 放弃、废止无效的政策，将资源和能量应用于增强和坚持更具建设性的目标。设法将各个子系统的目标协调一致，通常是设置一个更大的总体目标， *让所有参与者突破各自的有限理性*
**** 公地悲剧
     有限环境下的有限利性导致的类似囚徒困境。为个人或短期利益，放弃群体与长久利益。“公地悲剧”之所以产生，一个重要原因是资源的消耗与资源的使用者数量增长间的反馈缺失或时间延迟太长了。

     应对策略:
     - 教育 、劝诫 -- 法律、道德
     - 将公共资源私有化 -- 土地、水电等
     - 对公共资源进行管制 -- 通过监管者及使用者的互动，在行动和资源的状态之间建立了间接的联系，为了使这个反馈起作用，监管者必须有能力实施监管，并可以准确地把握公共资源的状态，同时也要有有效的威慑措施，并真心愿意维护整个社区的福利。比如十字路口的红灯，波段的分配
**** 目标侵蚀
     一些系统不只是对试图改变它的政策措施具有阻力，竭力维持在一个大家谁都不愿意看到的不良状态，更为糟糕的是，它们还在持续的恶化。简言之就是：温水煮青蛙，破罐子破摔。期望的系统状态会感知到状态的影响。当感知到绩效水平的下滑，目标也相应的下调。原本在调节回路作用下，系统应该维持在一个可接受的水平上，但因为“目标侵蚀”，使得被一个具有向下趋势的增强回路所掩盖。

     应对策略：
     - 不管绩效如何，都要保持一个绝对的标准
     - 不断将目标与过去的最佳标准对照，而不是和最差的相比
**** 竞争升级
     竞争升级是一种增强型回路，是以指数级方式发展起来的，一旦超过某个限度，其激化的速度会超出绝大数人的想象。抽象概括就是：当系统中一个存量的抓过你太是取决于另外一个存量的状态，并试图超过对方时，就构成了增强回路。

     应对策略:
     - 某一方当方面让步，从而切断增强回路的运作
     - 双方进行协商，引入调节回路，对竞争进行一些限制
**** 富者愈富：竞争排斥
     如果在系统中，竞争的赢家会持续地强化其进一步获胜地手段，这就形成了增强回路。如果这一回路不受限制地运转下去，赢家最终会通吃，输家则被小苗

     应对策略：
     - 多元化。但多元化会形成新的市场竞争，竞争排斥无法根本杜绝
     - 植入反馈回路，避免任何一个竞争者完全控制，使富者愈富反馈回路处于可控的状态。比如反垄断法
**** 转嫁负担：上瘾
     当面对一个系统性问题时，如果采用的解决方案根本无助于解决潜在的根本问题，只是缓解（或掩饰）了问题的症状时，就会产生转嫁负担、依赖性和上瘾的状况。不管是麻痹个人感官的物质，还是把潜在麻烦隐藏起来的政策，人们选择的干预行动都不能解决真正的问题。

     如果选择并实施的干预措施，导致系统原本的自我调适能力萎缩或受到侵蚀，就会引发一个破坏性的增强回路。系统自我调适能力越差，就需要越多的干预措施；而这会使得系统的自我调适变得更差，不得不更多地依赖外部干预者

     应对策略:
     - 提前预防，防止跌入陷阱
     - 想办法恢复或增强系统自身解决问题的能力，然后自己择机抽身退出
**** 规避规则
     规避规则意味着，采取一些迂回或变通措施，虽然名义上遵守或不违反规则的条文要求，但在本质上规避了系统规则的原本意图。如果规避规则的行为导致系统产生严重的扭曲或不自然的行为，就是一个需要警惕的问题：一旦失去控制，系统将会具有强大的破坏性。

     应对策略
     - 通过强化规则及其实施力度，试图扑灭、镇压规避规则的行动
     - 把规避规则看作有用的反馈，对规则进行修订、改善、废除，或给予更好的解释，实现规则本来的目的。
**** 目标错位
     影响系统行为最有力的方式之一就是，调整它的目的或目标。这是因为，目标设定了系统的方向，定义了需要采取校正措施的差距，并指示着调节回路运作的预期状态以及成败。如果目标定义不当，不能测量应该被测量的东西，不能真实地反映系统的状态，那么系统就不可能产出期望的结果。

     应对策略：
     - 恰当地设定目标及基表，以反映系统真正的福利。一定要特别小心，不要将努力与结果混淆，否则系统将只产出特定的努力，而不是你期望的结果。
** 第三部分：改变系统
*** 第6章：系统之杠杆点：系统的12大变革方式
**** 12、数字：包括各种常数和参数
     通过数值（尤其是流量的大小）来调节系统是效力最低的一种方式，无法改变系统基本的结构。只有当我们实在没有其他方式时，才会把参数当做杠杆点
**** 11、缓冲器：比流量力量更大、更稳定的存量
**** 10、存量--流量结构：实体系统及其交叉节点
**** 09、时间延迟：系统对变化做出放映的速度
**** 08、调节回路：试图修正外界影响的反馈力量
**** 07、增强回路：驱动收益增长的反馈力量
**** 06、信息流：谁能获得信息的结构
**** 05、系统规则：激励、惩罚和限制条件
**** 04、自组织：系统结构增加、变化或进化的力量
     自组织是系统具有最高适应力的表现形式。一个能够自我进化的系统，可以通过改变自身，来适应各种变化，以维持生存
**** 03、目标：系统的目标或功能
**** 02、 *社会范式：决定系统之所以为系统的心智模式*
     社会公认的观念，一些潜在的基本假设以及关于社会现实本质的普遍看法，构成了社会的范式（paradigm），或者是一整套世界观，它们是人们普遍相信的、关于世界是如何运作的一系列基本假设、规则或信念。这些信念都是隐含的，因为在一个社会中，几乎每一个人都已经知道它们，因而无须特别申明

     范式是系统之所以成为系统的根源。根植于这些范式，产生了系统的目标和信息流、反馈、各种存量和流量，以及系统中的所有东西。系统的目标、结构、规则、时间延迟和各种参数，都受范式的直接影响
**** 01、 *超越范式*
     我们需要在自己的内心认识到各种范式的存在，并将这一点也视为一种范式，以赤子之心对待整体现实。这样才能进入一种“空”（not-knowing）的状态，进入佛教所讲的“开悟”境界
*** 第7章：与系统共舞：系统的15大生存法则
    - 跟上系统的节拍
    - 把你的心智模式展现在阳光下
    - 相信、尊重并分享信息
    - 谨慎地使用语言，并用系统的概念去丰富语言
    - 关注重要的，而不只是容易衡量的
    - 为反馈系统制定带有反馈功能的政策
    - 追求整体利益
    - 聆听系统的智慧
    - 界定系统的职责
    - 保持谦逊，做一名学习者
    - 庆祝复杂性
    - 扩大时间的范围
    - 打破各种清规戒律
    - 扩大关切范围
    - 不要降低“善”的标准
